import { chromium } from 'playwright'
const BASE = process.env.BASE || 'http://localhost:5173/'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
const errors = []
page.on('pageerror', (e) => errors.push(e.message))
page.on('console', (m) => m.type() === 'error' && errors.push(m.text()))
await page.goto(BASE + '#/shield?sample=loan')
await page.waitForTimeout(800)
await page.getByRole('button', { name: 'Use an example reply' }).click()
await page.waitForTimeout(300)
console.log('RESTORED:\n' + (await page.locator('pre[aria-label="Restored reply"]').innerText()))
console.log('COUNT:', await page.getByText(/\d+ restored/).innerText())
const t0 = Date.now()
await page.getByRole('switch', { name: 'Enable on-device AI' }).click()
await page.getByText('Active. Runs in a background worker').waitFor({ timeout: 240000 })
console.log('AI ready in', Date.now() - t0, 'ms')
await page.waitForTimeout(2500)
console.log('MASKED WITH AI:\n' + (await page.locator('pre[aria-label="Masked text"]').innerText()))
await page.getByRole('button', { name: 'Cover letter' }).click()
await page.waitForTimeout(3000)
console.log('COVER LETTER:\n' + (await page.locator('pre[aria-label="Masked text"]').innerText()))
await page.screenshot({ path: 'e2e/shots/shield-ai.png', fullPage: true })
console.log('errors', errors)
await browser.close()
