// Records a captioned walkthrough of Veil (Playwright video, 1280x800).
import { chromium } from 'playwright'
import { renameSync, mkdirSync } from 'node:fs'
const BASE = process.env.BASE || 'http://localhost:4173/'
mkdirSync('e2e/video', { recursive: true })
const browser = await chromium.launch()
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 }, recordVideo: { dir: 'e2e/video', size: { width: 1280, height: 800 } }, acceptDownloads: true })
const page = await ctx.newPage()
const wait = (ms) => page.waitForTimeout(ms)
const caption = (text) =>
  page.evaluate((t) => {
    let el = document.getElementById('demo-caption')
    if (!el) {
      el = document.createElement('div')
      el.id = 'demo-caption'
      el.style.cssText = 'position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:9999;max-width:980px;padding:12px 18px;border-radius:10px;background:rgba(22,20,15,.92);color:#f3f0e8;font:500 17px/1.4 "Inter Tight Variable",system-ui,sans-serif;box-shadow:0 12px 30px -10px rgba(0,0,0,.5);text-align:center;pointer-events:none'
      document.body.appendChild(el)
    }
    el.textContent = t
  }, text)
const smoothScroll = (y) => page.evaluate((y) => window.scrollTo({ top: y, behavior: 'smooth' }), y)
const center = (loc) => loc.evaluate((el) => el.scrollIntoView({ block: 'center', behavior: 'smooth' }))

await page.goto(BASE)
await wait(1600)
await caption('Veil: share the document, not your identity. Everything runs inside your browser.')
await wait(3200)
await smoothScroll(640)
await caption('Two tools: a safe ID copy maker and a privacy shield for AI prompts.')
await wait(3000)
await smoothScroll(0)
await wait(600)
await page.getByRole('button', { name: /Make a safe ID copy/ }).click()
await wait(900)
await caption('Drop a photo or PDF, or try a sample: a phone photo of a tenant form.')
await wait(1800)
await page.getByRole('button', { name: 'Tenant form (phone photo)' }).click()
await caption('Text recognition runs locally (self-hosted Tesseract). Nothing is uploaded.')
await page.getByText('Hidden on this copy').waitFor({ timeout: 120000 })
await wait(800)
await smoothScroll(60)
await caption('Aadhaar verified by its checksum, PAN, bank account, UPI, phone, names, addresses and the QR code.')
await wait(4200)
await center(page.getByRole('heading', { name: 'Hidden data in the file' }))
await caption('The photo also carries GPS coordinates of where it was taken. Veil strips all metadata on export.')
await wait(3800)
await center(page.getByRole('heading', { name: 'Purpose stamp' }))
await wait(700)
await caption('Stamp the copy with who it is for and why.')
await page.getByPlaceholder('e.g. Hotel Sunrise, Goa').pressSequentially('Sharma Estates', { delay: 60 })
await page.getByPlaceholder('e.g. check-in').pressSequentially('rental verification', { delay: 50 })
await wait(900)
await smoothScroll(0)
await wait(500)
await page.getByRole('radio', { name: 'Preview copy' }).click()
await caption('Only the last 4 Aadhaar digits stay visible (UIDAI style). QR blacked out. A traceable reference is printed.')
await wait(1500)
await smoothScroll(250)
await wait(3000)
await smoothScroll(760)
await wait(3000)
const [dl] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: /Download safe copy/ }).click()])
await dl.saveAs('e2e/video/exported.png')
await smoothScroll(250)
await caption('Downloaded: redactions burned into pixels, no hidden text, logged in your on-device ledger.')
await wait(3000)
await page.getByRole('link', { name: 'Ledger' }).click()
await wait(900)
await caption('Copy turned up somewhere it should not? Drop it in: Veil reads the reference off the image.')
await wait(1600)
await page.locator('input[type=file]').first().setInputFiles('e2e/video/exported.png')
await page.getByText(/You gave this copy to/).waitFor({ timeout: 90000 })
await caption('…and tells you exactly who you gave it to, and for what.')
await wait(3800)
await page.getByRole('link', { name: 'Prompt shield' }).click()
await wait(700)
await page.getByRole('button', { name: 'Loan query' }).click()
await caption('Prompt shield: personal details become placeholders before you ask ChatGPT, Gemini or Claude.')
await wait(4200)
await smoothScroll(560)
await page.getByRole('button', { name: 'Use an example reply' }).click()
await caption('Paste the reply back and your real details are restored, on this device.')
await wait(4200)
await smoothScroll(0)
await page.getByRole('button', { name: 'Bug report with keys' }).click()
await caption('It also catches API keys, database passwords and OTPs before they leak.')
await wait(3600)
await page.getByRole('link', { name: 'Veil home' }).click()
await wait(600)
await caption('Open source, offline-capable, no server.  satanrayshe.github.io/veil')
await wait(3200)
const video = page.video()
await ctx.close()
const path = await video.path()
renameSync(path, 'e2e/video/veil-demo.webm')
await browser.close()
console.log('video saved')
